name: input test
on: 
  workflow_dispatch:
    inputs:
      app_flavour:
        description: 'Flavour ( BSMART | DEA | ecc...)'
        required: true
        default: 'BSMART'
      app_channel:
        description: 'Channel ( production_v2 | production | development | cd | usb )'
        required: true
        default: 'development'
        
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "App flavour ${{ github.event.inputs.app_flavour }}"
        echo "App channel: ${{ github.event.inputs.app_channel }}"
