name: multi os test

on:
  push:
    paths:
      - '**/multios.yml'
        
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'windows-2022']
        
    steps:
      - name: set env
        shell: bash
        run: echo "FOO=bar" >> $GITHUB_ENV

      - name: print env
        shell: bash
        run: echo "$FOO"

      - name: run commmand
        shell: bash
        id: download
        run: |
          mkdir out
          echo "::set-output name=download-path::$(echo $(pwd)/out)"
          JSON=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/tags)
          echo "$JSON"
          JSON_F=$(echo "$JSON" |
            jq '.[] | select(.name ) | [ .name, .tarball_url ] | @csv')
          echo "$JSON_F"
          echo "$JSON_F" |
            tr -d '"\' |
            while IFS=$',' read -r name tarball_url; do
              curl -L \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H 'Accept: application/octet-stream' $tarball_url > "out/$name.tar.gz" ;
              curl https://dev-files.blender.org/file/download/bwdp5reejwpkuh5i2oak/PHID-FILE-nui3bpuan4wdvd7yzjrs/sample.tar.gz > out/sample.tar.gz
            done
            
      - name: list dir
        run: ls -R out
      
      - name: untar
        run: |
          tar -xf sample.tar.gz
        working-directory: out
        
      - name: zip
        if: matrix.os != 'windows-2022'
        run: zip -r -X -y -9 -q out.zip .
        working-directory: out
          
      - name: 7zip
        if: matrix.os == 'windows-2022'
        run: Start-Process 'C:\Program Files\7-Zip\7z' -ArgumentList 'a -mx9 out.zip .'
        working-directory: out
