# This is a basic workflow to help you get started with Actions

name: Windows build

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    paths:
      - '**/win.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: test git-bash
        run: '"c:\Program Files\Git\git-bash.exe"'
      
      - name: yarn install
        run: yarn install

      - name: build and package
        run: |
          yarn build
          yarn package
